### PR TITLE
Minor fix for LR radios on the BETA TFAR

### PR DESCRIPTION
**Pull request by Tirpitz93**
I was getting an error when trying to load LR radio settings, when using the BETA, this seems to fix it.

### CODE REVIEW

**Comment by M3ales** [comment]
Thanks for the PR to start^^

I'd like to preserve compatibility with 0.9.12, since that's my own unit's use case, but we can probably throw a version check in there to keep that. I spent some time in tfar beta's repo and it doesn't look like they've added any specific client version check functionality which is a shame.

We could perhaps look at doing something along the lines of:
```sqf
if (isClass(configFile >> "CfgPatches" >> "tfar_core")) then{
    // version > 1.0
    [_targetLR, _radioData] call TFAR_fnc_setLrSettings;
}
else
{
    // version < 1.0
    [_targetLR select 0, _targetLR select 1, _radioData] call TFAR_fnc_setLrSettings;
}
```

It may be worth just doing this check during postInit and caching it, then have it as a function so we can make changes specific for 1.0 Beta, but I'm not sure how much else isn't working?

**Comment by Tirpitz93** [comment]
I would be happy to add this check to the action, as it is unlikely to be used very often, and so would have limited impact on performance

**Comment by M3ales** [comment]
@RTO-Chatter don't have keys to push anything and can't reach you on discord. Mind getting in touch to pass bikeys on and/or the repo so it can be updated?

**Comment by Tirpitz93** [comment]
Just to note I dont believe this has a version check yet

**Comment by M3ales** [comment]
Took forever but I'm going to do a few passes now for beta compat since my unit doesn't use old tfar anymore.

**Pull request merged**
